name: workfloooow
on: push
jobs:
  jobaya1:
   runs-on: ubuntu-latest
   steps:
     - name: get code
       uses: actions/checkout@v3
     - name: install node
       uses: actions/setup-node@v4  
     - name: install depedencies
       run: npm ci
     - name: testing
       run: npm run test
     - name: build
       run: npm run build


